# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run lint && npm run solhint
    - run: npm run generate
    - run: npm run test

    - name: Download previous benchmark data
      id: benchmark-cache
      uses: actions/cache@v2
      with:
        path: baseline.txt
        key: ${{ runner.os }}-benchmark

    - name: "Show previous run"
      if:  steps.benchmark-cache.outputs.cache-hit == 'true'
      run: cat baseline.txt

    - name: "[only PR] Run PR benchmark"
      if: github.ref != 'refs/heads/master'
      run: npm run bench

    - name: "[only master] Run master benchmark"
      if: github.ref == 'refs/heads/master'
      run: npm run bench | tee baseline.txt
