# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run generate
    - run: npm run test
    - name: benchmark
      if: github.ref == 'refs/heads/master'
      run: npm run bench > baseline.txt
    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master'
      with:
        name: baseline
        path: baseline.txt
    - name: Download baseline
      if: github.ref != 'refs/heads/master'
      uses: actions/download-artifact@v2
      with:
        name: baseline
    - run: cat baseline.txt && npm run bench
